import type {CourseListItem, UserDto} from '../api/types';

/** Shown in Profile / headers when API or auth fails and we fall back to the full app shell. */
export const STATIC_DEMO_USER: UserDto = {
  id: 'static-demo',
  studentId: 'DEMO-001',
  email: 'demo@matchmyuni.app',
  firstName: 'Demo',
  lastName: 'Student',
  country: 'United States',
  countryCode: '+1',
  contact: '5550100',
  avatarUrl: null,
  referralCodeUsed: null,
  createdAt: new Date().toISOString(),
};

/** Discover deck + CourseDetails + StartApplication in static demo (no API). */
export const STATIC_DISCOVER_COURSES: CourseListItem[] = [
  {
    id: 910001,
    universityId: 1,
    universityName: 'Kingsbridge University',
    name: 'MSc Data Science & AI',
    description:
      'Hands-on machine learning, NLP, and cloud deployment — demo card for app flow.',
    country: 'United Kingdom',
    city: 'London',
    applicableTuitionFee: 28500,
    applicationFee: 75,
    currency: 'GBP',
    currencySymbol: '£',
    category: 'STEM',
    degreeLevel: 'Masters',
    duration: 2,
    intakes: ['September', 'January'],
    language: 'English',
    scholarshipOnTuitionFee: 'Up to 20%',
    isPrime: true,
    tags: ['STEM', 'Employability'],
    minimumGPA: '3.0 / 4.0',
  },
  {
    id: 910002,
    universityId: 2,
    universityName: 'Pacific Coast College',
    name: 'BBA International Business',
    description: 'Global strategy, finance, and marketing — demo flow only.',
    country: 'Canada',
    city: 'Vancouver',
    applicableTuitionFee: 22000,
    applicationFee: 50,
    currency: 'CAD',
    currencySymbol: 'C$',
    category: 'Business',
    degreeLevel: 'Bachelors',
    duration: 4,
    intakes: ['September'],
    language: 'English',
    isPrime: false,
    tags: ['Business'],
  },
  {
    id: 910003,
    universityId: 3,
    universityName: 'Nordic Tech Institute',
    name: 'MEng Software Engineering',
    description: 'Distributed systems and product engineering — demo.',
    country: 'Sweden',
    city: 'Stockholm',
    applicableTuitionFee: 18000,
    applicationFee: 0,
    currency: 'EUR',
    currencySymbol: '€',
    category: 'Engineering',
    degreeLevel: 'Masters',
    duration: 2,
    intakes: ['August'],
    language: 'English',
    scholarshipOnTuitionFee: 'Merit-based',
    isPrime: true,
    tags: ['Engineering', 'Tech'],
  },
];
