import {StyleSheet} from 'react-native';
import {colors} from '../../../utils/colors';
import {SCREEN_H_PADDING} from '../../../utils/theme';

export const profileStyles = StyleSheet.create({
  screen: {flex: 1, backgroundColor: colors.background},
  scroll: {paddingHorizontal: SCREEN_H_PADDING},
  pageTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: colors.navy,
    letterSpacing: -0.24,
    lineHeight: 28,
    marginBottom: 16,
  },
  section: {
    backgroundColor: colors.white,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 16,
    marginBottom: 14,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.navy,
    letterSpacing: -0.16,
    lineHeight: 22,
    marginBottom: 12,
  },
  sectionTitleStandalone: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.navy,
    letterSpacing: -0.16,
    lineHeight: 22,
    marginBottom: 0,
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  infoLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.textSecondary,
    lineHeight: 18,
  },
  infoValue: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.navy,
    lineHeight: 18,
    textAlign: 'right',
    flex: 1,
    marginLeft: 12,
  },
  settingsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  settingsLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.navy,
    lineHeight: 18,
  },
  chevron: {fontSize: 18, color: colors.textSecondary, fontWeight: '400'},
  progressTrack: {
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.profileProgressTrack,
    overflow: 'hidden',
    marginTop: 8,
    marginBottom: 6,
  },
  progressFill: {
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.accentTeal,
  },
  progressHint: {
    fontSize: 12,
    fontWeight: '500',
    color: colors.textSecondary,
    lineHeight: 16,
  },
  editBtn: {
    alignSelf: 'center',
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 1000,
    borderWidth: 1,
    borderColor: colors.primary,
    marginBottom: 14,
  },
  editBtnLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.primary,
    lineHeight: 18,
  },
  logout: {
    alignItems: 'center',
    paddingVertical: 16,
    marginTop: 4,
    marginBottom: 24,
  },
  logoutLabel: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.primary,
    lineHeight: 22,
  },
});
