/**
 * Central user-visible copy. Extend with i18n later.
 */
export const en = {
  appName: 'Match My Uni',
  tagline: 'Your future university is waiting.',
  poweredBy: 'POWERED BY EDUDITE',
  terms: {
    prefix: 'By continuing, you agree to our',
    tos: 'Terms of Service',
    and: 'and',
    privacy: 'Privacy Policy',
  },
  socialProof: 'Join 12,000+ students',
  getStarted: 'Get started',
  logIn: 'Log in',
  back: 'Back',
  skip: 'Skip',
  continue: 'Continue',
  findMatches: 'Find my matches',
  whoAreYou: {title: 'Who are you?', subtitle: 'Choose your role to get started.'},
  student: {
    title: "I'm a Student",
    sub: 'Find university that match my profile',
  },
  agent: {
    title: "I'm an Agent",
    sub: 'Helping students find their perfect university',
  },
  partner: 'University partner or admin? ',
  signInHere: 'Sign in here',
  signupMethod: {
    title: 'How do you want to sign up?',
    subtitle: 'Choose your preferred method.',
    email: 'Continue with email',
    phone: 'Continue with phone number',
    google: 'Continue with Google',
    apple: 'Continue with Apple',
    or: 'or',
  },
  emailScreen: {title: 'Get going with email', subtitle: 'We will only use it for your account.'},
  emailLabel: 'Email address',
  password: {
    title: 'Create a password',
    subtitle: 'Make it strong',
    placeholder: 'Password',
    requirements: {
      len: 'At least 8 characters',
      upper: 'One uppercase letter',
      number: 'One number',
      special: 'One special character',
    },
  },
  accountDetails: {
    title: 'A few more details',
    subtitle: 'We need this to create your account.',
    first: 'First name',
    last: 'Last name',
    phone: 'Phone number',
    country: 'Country',
    firstNameMinLength: 'First name must be at least 2 characters',
    lastNameMinLength: 'Last name must be at least 2 characters',
  },
  study: {
    title: 'What do you want to study?',
    subtitle: 'Pick everything that interests you',
  },
  location: {
    title: 'Where do you want to study?',
    subtitle: 'Pick countries you are interested in',
    search: 'Search country',
  },
  timeline: {
    title: 'When are you planning to start?',
    subtitle: "No pressure — we'll match you accordingly.",
  },
  budget: {
    title: "What's your budget range?",
    subtitle: 'Per year, including tuition. We will find scholarships too.',
    hint: 'This is annual tuition only — not living costs. Scholarships can reduce any tier.',
    nearDone: 'Almost there! Your matches are being prepared.',
  },
  login: {title: 'Welcome back', subtitle: 'Sign in to continue your journey.'},
  forgotPassword: {
    title: 'Forgot your password?',
    subtitle: "Enter your email and we'll send you a reset link.",
    emailLabel: 'Email address',
    rememberPrefix: 'Remember your password?',
    signIn: 'Sign in.',
    successTitle: 'Check your email',
    successBody: 'We sent a link to reset your password to',
    successCta: 'Alright',
  },
  resetPassword: {
    title: 'Reset your password?',
    subtitle: 'Create a strong new password below.',
    newLabel: 'New password',
    confirmLabel: 'Confirm password',
    requirementsTitle: 'Your password must include:',
    noMatch: 'Passwords do not match.',
    cta: 'Reset password',
    tokenLabel: 'Reset token (from your email link)',
    successTitle: 'Password reset!',
    successBody: 'Your password has been updated. You can now sign in.',
  },
  phoneEntry: {
    title: 'Get going with phone number',
    subtitle: 'Enter your number to get started.',
    placeholder: '(555) 123-4567',
    pickerTitle: 'Select country code',
    pickerSearch: 'Search country',
  },
  preparing: {
    headline: 'Find universities that fit your profile',
    sub: 'Takes less than a minute.',
  },
  signupTutorial: {
    recommended: 'Recommended',
    rightSwipe:
      'Right swipe to add in recommendation\nand also shortlisted',
    leftSwipe: 'Left swipe to remove from recommendation',
    tapDetail: 'On click to view course detail page',
    next: 'Next',
    skip: 'Skip',
    done: 'Done',
    goHome: 'Go to home',
  },
  agentPreparing: {
    headline: 'Setting up your agent account',
    sub: 'This will only take a moment.',
  },
  comingSoon: {
    google: 'Google sign-in is not yet available in this version. Please use email.',
    apple: 'Apple sign-in is not yet available in this version. Please use email.',
    phone: 'Phone verification coming soon. You can still add your number in account details.',
  },
  errors: {
    network: 'Check your connection and try again.',
    generic: 'Something went wrong. Please try again.',
    invalidEmail: 'Enter a valid email address.',
    passwordWeak: 'Please meet all password requirements.',
  },
  applicationsTab: {
    title: 'Applications',
    shortlist: 'Shortlist',
    applied: 'Applied',
    startApplication: 'Start Application →',
    remove: 'Remove',
    trackStatus: 'Track Application status →',
    trackTitle: 'Application Status',
    trackBack: 'Back',
    trackLoadFailed: 'Could not load application details.',
    currentStatus: 'Current status',
    progressTitle: 'Application progress',
    feesTitle: 'Fees & payments',
    emptyShortlistTitle: 'No shortlisted courses',
    emptyShortlistSub: 'Swipe right on Discover or tap Shortlist on a course to save it here.',
    emptyAppliedTitle: 'No applications yet',
    emptyAppliedSub: 'Start an application from your shortlist or course details.',
  },
  applicationFlow: {
    submittedTitle: 'Application Submitted!',
    submittedSubtitlePrefix: "We've received your application for",
    submittedNextTitle: 'What happens next?',
    submittedNextBody:
      'Our team will review your documents and keep you updated on your application status in the Applications tab.',
    viewApplications: 'View My Applications',
    done: 'Back to Home',
    paymentTitle: 'Application Fee',
    paymentDue: 'Application fee due',
    paymentPlaceholder:
      'Online payment is coming soon. Your application has been created — you can complete payment later from the Applications tab.',
    paymentContinue: 'Continue',
    allDocsReady: 'All documents ready — you can submit your application.',
    uploadAllDocs: 'Upload all required documents to continue.',
    selectIntake: 'Select intake',
    shortlistAdded: 'Added to shortlist',
    shortlistRemoved: 'Removed from shortlist',
    submitConfirmTitle: 'Submit Application',
    submitConfirmBody: 'Apply for this course with the selected intake?',
    noIntake: 'No open intake is available for this course right now.',
    courseLoadFailed: 'Could not load course details. Go back and try again.',
  },
} as const;

export type StringTable = typeof en;
